FROM node:18 as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Set the environment variable to fix crypto issues
ENV NODE_ENV=production

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]