FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
COPY . .

ARG VITE_API_URL=
ENV VITE_API_URL=$VITE_API_URL
ENV NPM_CONFIG_PRODUCTION=false
ENV NODE_ENV=development

RUN npm install --no-audit --no-fund && npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
