FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY . .

ENV NPM_CONFIG_PRODUCTION=false
ENV NODE_ENV=development

RUN npm install --no-audit --no-fund

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
