FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY . .

ENV NPM_CONFIG_PRODUCTION=true
ENV NODE_ENV=production

RUN npm install --omit=dev --no-audit --no-fund

RUN mkdir -p uploads/houses

EXPOSE 3000

CMD ["npm", "start"]
